export const RESERVA_STATUS = Object.freeze({
  AGUARDANDO_PAGAMENTO: "aguardando_pagamento",
  CONFIRMADA: "confirmada",
  CANCELADA: "cancelada",
  EXPIRADA: "expirada",
  FINALIZADA: "finalizada",
});

export const RESERVA_STATUS_LISTA = Object.freeze(Object.values(RESERVA_STATUS));

export const RESERVA_STATUS_SEM_CONFLITO_DE_HORARIO = Object.freeze([
  RESERVA_STATUS.CANCELADA,
  RESERVA_STATUS.EXPIRADA,
]);

export const RESERVA_STATUS_COM_HORARIO_ATIVO = Object.freeze([
  RESERVA_STATUS.AGUARDANDO_PAGAMENTO,
  RESERVA_STATUS.CONFIRMADA,
]);

export const RESERVA_STATUS_BLOQUEIAM_PAGAMENTO = Object.freeze([
  RESERVA_STATUS.CANCELADA,
  RESERVA_STATUS.EXPIRADA,
  RESERVA_STATUS.FINALIZADA,
]);
