import { Router } from "express";
import arquivoRoutes from "../modules/arquivos/arquivo.routes.js";
import auditoriaRoutes from "../modules/auditoria/auditoria.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import clienteRoutes from "../modules/clientes/cliente.routes.js";
import comunicadoRoutes from "../modules/comunicados/comunicado.routes.js";
import horarioRoutes from "../modules/horarios/horario.routes.js";
import modalidadeRoutes from "../modules/modalidades/modalidade.routes.js";
import pagamentoRoutes from "./pagamentoRoutes.js";
import quadraRoutes from "../modules/quadras/quadra.routes.js";
import relatorioRoutes from "../modules/relatorios/relatorio.routes.js";
import reservaRoutes from "./reservaRoutes.js";
import verificacaoEmailRoutes from "../modules/verificacao-email/verificacaoEmail.routes.js";
import webhookRoutes from "./webhookRoutes.js";

const router = Router();
router.use("/auth", authRoutes);
router.use("/clientes", clienteRoutes);
router.use("/verificacao-email", verificacaoEmailRoutes);
router.use("/quadras", quadraRoutes);
router.use("/modalidades", modalidadeRoutes);
router.use("/horarios", horarioRoutes);
router.use("/reservas", reservaRoutes);
router.use("/pagamentos", pagamentoRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/comunicados", comunicadoRoutes);
router.use("/arquivos", arquivoRoutes);
router.use("/relatorios", relatorioRoutes);
router.use("/logs", auditoriaRoutes);
export default router;
